### PR TITLE
minor changes

### PR DESCRIPTION
**Pull request by pduchnovsky**
- removed transitionPlay from images, since it's applied to all body elements by default, this doubled it on imgs which looked kinda weird
- changed management of hexo icon, now it's the same way as others and it's moved a bit so it's no longer weird height compared to the  ❤
- improved readability of code within text - it was not easily noticeable which part of text is actual code (``code``)
- darkmode text reduced brightness because it was too high, tweaked code background so it's distinguished in dark mode, added images shadow, tweaked scrollbar design so it no longer has round corners
- added anonymized (all possible 'additional' tracking options disabled) google analytics script
- moved theme color styles to separate file
- Moved to local fonts instead of google because it was prolonging loading the page and lowering pagespeed scode
- Added checking if menu entry is defined, if not, not showing it
- Added 'gallery' function via css - allowing to show two side by side images by defining certain alt text
- Increased fonts size a bit

im basically moving some custom features I have on my personal site back to the minima repository :)

### CODE REVIEW

**Comment by adisaktijrs** [comment]
Thanks again @pduchnovsky. I never thought I would get this much help in this project haha. I'll be updating the demo site and documentation soon. Thank you very much.

**Comment by pduchnovsky** [comment]
Absolutely not a problem, I enjoy it :)

**Comment by pduchnovsky** [comment]
^ I added check if function obfuscate() from hexo-helper-obfuscate plugin is available, if it is, then it obfuscates email in html code
If it's not available then it simply puts email in normal format there

btw, this is performance now:
image

Could be better if you'd switch fonts to local alternatives for each browser, such as :
```
font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto",
    "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji",
    "Segoe UI Symbol";
```

This is how it looks with these:
image



If you want, I can include this change of font in this PR.

**Comment by adisaktijrs** [comment]
I saw your code for these improvements, I personally adore your way to make this theme better. I learned from it as well tbh haha.
Anyway for the font, I think I prefer to make the Minima original font as it is since I think the current performance (as img above) is already so much better. Big thanks!

**Pull request merged**
