### PR TITLE
some little problem fixed,and the function searching 😃

### PR DESCRIPTION
**Pull request by jinzhongjia**
I fix these problems and add an  interesting feature:

* When the meta tag about image in the layout page is set to empty, it will still appear in the generated file
* In the layout page, the introduction of the search page is added, and some JS that do not need to be loaded immediately are changed to defer
* The search page and JS of search are added, but 'hexo generator search' needs to be installed and the plug-in output JSON needs to be configured according to its documents

And I plan to optimize the function of clicking to enlarge the picture in a period of time. The interactive experience on mobile devices is not good🤔

### CODE REVIEW

**Comment by jinzhongjia** [comment]
If you want to see the actual effect of search, welcome to my blog: [jinzh](https://jinzh.me/)

**Comment by jinzhongjia** [comment]
em...... In the current pull request, there is a small error that causes the pic function to fail. After the pull is pulled, I will immediately restart a pull request to solve the problem I mentioned above

**Comment by adisaktijrs** [comment]
Wow, it's a big PR. I love the search feature!
Anyway, if you don'y mind could you close this PR, so you can fix that pic function issue first and then making the final PR?

**Comment by jinzhongjia** [comment]
ok,i will make a new PR😘

**Comment by adisaktijrs** [comment]
Okay, I'll wait for it😉

**Pull request closed without merging**
